/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contador;

/**
 *
 * @author User
 */
public class Exibir extends javax.swing.JFrame {

    /**
     * Creates new form Exibir
     */
    public Exibir() {
        initComponents();
    }

    Exibir(Moedas valor) {
        
    }
    public void exportaValores(int N100,int N50,int N20,int N10, int N5, int N2, int M1, int M50, int M25, int M10, int M5,String total){
        //int N100=valor.getN100();
       // System.out.println(N100);
        RN100.setText(String.valueOf(N100));
        RN50.setText(String.valueOf(N50));
        RN20.setText(String.valueOf(N20));
        RN10.setText(String.valueOf(N10));
        RN5.setText(String.valueOf(N5));
        RN2.setText(String.valueOf(N2));
        
        RM1.setText(String.valueOf(M1));
        RM50.setText(String.valueOf(M50));
        RM25.setText(String.valueOf(M25));
        RM10.setText(String.valueOf(M10));
        RM5.setText(String.valueOf(M5));
        Total.setText(String.valueOf(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rodape = new javax.swing.JLabel();
        N100 = new javax.swing.JLabel();
        N50 = new javax.swing.JLabel();
        N20 = new javax.swing.JLabel();
        N10 = new javax.swing.JLabel();
        N5 = new javax.swing.JLabel();
        N2 = new javax.swing.JLabel();
        M1 = new javax.swing.JLabel();
        M50 = new javax.swing.JLabel();
        M25 = new javax.swing.JLabel();
        M10 = new javax.swing.JLabel();
        M5 = new javax.swing.JLabel();
        RN100 = new javax.swing.JLabel();
        RN50 = new javax.swing.JLabel();
        RN20 = new javax.swing.JLabel();
        RN10 = new javax.swing.JLabel();
        RN5 = new javax.swing.JLabel();
        RN2 = new javax.swing.JLabel();
        RM1 = new javax.swing.JLabel();
        RM50 = new javax.swing.JLabel();
        RM25 = new javax.swing.JLabel();
        RM10 = new javax.swing.JLabel();
        RM5 = new javax.swing.JLabel();
        M6 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 350));
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        jLabel1.setText("Tudo pronto!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contador/2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 260, 270, 30);

        Rodape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contador/3.png"))); // NOI18N
        getContentPane().add(Rodape);
        Rodape.setBounds(0, 260, 430, 30);

        N100.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N100.setText("R$100,00  - ");
        getContentPane().add(N100);
        N100.setBounds(20, 60, 80, 20);

        N50.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N50.setText("R$50,00   -");
        getContentPane().add(N50);
        N50.setBounds(20, 90, 80, 20);

        N20.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N20.setText("R$20,00   -");
        getContentPane().add(N20);
        N20.setBounds(20, 120, 80, 20);

        N10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N10.setText("R$10,00    -");
        getContentPane().add(N10);
        N10.setBounds(20, 150, 80, 20);

        N5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N5.setText("R$5,00     -");
        getContentPane().add(N5);
        N5.setBounds(20, 180, 80, 20);

        N2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        N2.setText("R$2,00     -");
        getContentPane().add(N2);
        N2.setBounds(20, 210, 80, 20);

        M1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        M1.setText("R$1,00  -");
        getContentPane().add(M1);
        M1.setBounds(190, 60, 70, 20);

        M50.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        M50.setText("R$0,50  -");
        getContentPane().add(M50);
        M50.setBounds(190, 90, 70, 20);

        M25.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        M25.setText("R$0,25  -");
        getContentPane().add(M25);
        M25.setBounds(190, 120, 70, 20);

        M10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        M10.setText("R$0,10   -");
        getContentPane().add(M10);
        M10.setBounds(190, 150, 70, 20);

        M5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        M5.setText("TOTAL: R$");
        getContentPane().add(M5);
        M5.setBounds(300, 230, 70, 20);

        RN100.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN100);
        RN100.setBounds(90, 60, 90, 20);

        RN50.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN50);
        RN50.setBounds(90, 90, 90, 20);

        RN20.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN20);
        RN20.setBounds(90, 120, 90, 20);

        RN10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN10);
        RN10.setBounds(90, 150, 90, 20);

        RN5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN5);
        RN5.setBounds(90, 180, 90, 20);

        RN2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RN2);
        RN2.setBounds(90, 210, 90, 20);

        RM1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RM1);
        RM1.setBounds(250, 60, 120, 20);

        RM50.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RM50);
        RM50.setBounds(250, 90, 120, 20);

        RM25.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RM25);
        RM25.setBounds(250, 120, 120, 20);

        RM10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RM10);
        RM10.setBounds(250, 150, 120, 20);

        RM5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        getContentPane().add(RM5);
        RM5.setBounds(250, 180, 120, 20);

        M6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        M6.setText("R$0,05  -");
        getContentPane().add(M6);
        M6.setBounds(190, 180, 70, 20);

        Total.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        getContentPane().add(Total);
        Total.setBounds(370, 230, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exibir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Exibir().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel M1;
    private javax.swing.JLabel M10;
    private javax.swing.JLabel M25;
    private javax.swing.JLabel M5;
    private javax.swing.JLabel M50;
    private javax.swing.JLabel M6;
    private javax.swing.JLabel N10;
    private javax.swing.JLabel N100;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N20;
    private javax.swing.JLabel N5;
    private javax.swing.JLabel N50;
    private javax.swing.JLabel RM1;
    private javax.swing.JLabel RM10;
    private javax.swing.JLabel RM25;
    private javax.swing.JLabel RM5;
    private javax.swing.JLabel RM50;
    private javax.swing.JLabel RN10;
    private javax.swing.JLabel RN100;
    private javax.swing.JLabel RN2;
    private javax.swing.JLabel RN20;
    private javax.swing.JLabel RN5;
    private javax.swing.JLabel RN50;
    private javax.swing.JLabel Rodape;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
